spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    driver-class-name: org.postgresql.Driver
    password: admin
    username: admin
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect